repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
    -   id: check-docstring-first
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''
    hooks:
    -   id: autopep8
        args: [--in-place, --aggressive, --aggressive ]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: ''
    hooks:
    -   id: add-trailing-comma

-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8
